// SWAT Agro Chemicals Product Database
const PRODUCTS = {
    "FERTILIZER": [
        { "name": "NOVATEC CLASSIC", "technical": "NPK 12-08-16", "sizes": ["25 Kg"] },
        { "name": "NUTRI SAC - SOP", "technical": "Potosh 50%, Sulphur 18%", "sizes": ["25 Kg"] },
        { "name": "ORGEVIT", "technical": "Organic matter 25%", "sizes": ["25 Kg"] },
        { "name": "SOP GRANULARS", "technical": "Potosh 50%, Sulphur 18%", "sizes": ["25 Kg"] },
        { "name": "ULTRASOL CUCUMBER 15-08-26", "technical": "NPK 15-08-26", "sizes": ["15 Kg"] },
        { "name": "ULTRASOL MAGNUM FLEX 13-2-43", "technical": "NPK 13:02:43", "sizes": ["25 Kg"] },
        { "name": "ULTRASOL MAGNUM FLEX 16-22-23", "technical": "N=16%, P=22%, K=23%", "sizes": ["25 Kg"] },
        { "name": "ULTRASOL MAGNUM P44 18-44-0", "technical": "N=18%, P=44%", "sizes": ["25 Kg"] },
        { "name": "ULTRASOL PEPPER 14-07-29", "technical": "NPK 14-07-29", "sizes": ["15 Kg"] },
        { "name": "ULTRASOL SOP", "technical": "K 0-0-51 +18(S)", "sizes": ["25 Kg"] },
        { "name": "ULTRASOL TOMATO 13-07-31", "technical": "NPK 13-07-31", "sizes": ["15 Kg"] }
    ],
    "FUNGICIDES": [
        { "name": "AIR ONE 20% SC", "technical": "Copper Oxychloride 20% + Copper Hydroxide", "sizes": ["360 Ml"] },
        { "name": "BAMBOOSA 56%SC", "technical": "Chlorothalonil + Azoxystrobin", "sizes": ["250 Ml"] },
        { "name": "COBOX 50WP", "technical": "Copper Oxychloride 50%", "sizes": ["500 Gm", "1 Kg"] },
        { "name": "DOMARK XL", "technical": "Azoxystrobin 100g/L + Tetraconazole 80g/L", "sizes": ["200 Ml"] },
        { "name": "FANTIC M", "technical": "Benalaxyl-M 4% + Mancozeb 65%", "sizes": ["250 Gm", "500 Gm", "300 Gm"] },
        { "name": "MIXTAN 60% SC", "technical": "Dimethomorph 8% + Chlorothalonil 40%", "sizes": ["330 Ml"] },
        { "name": "NANOK 25%SC", "technical": "Flutriafol + Azoxystrobin", "sizes": ["200 Ml", "400 Ml"] },
        { "name": "NETZSCHWEFEL STULLN DF", "technical": "Sulfur 80% DF", "sizes": ["1 Kg"] },
        { "name": "POLYRAM DF", "technical": "Metiram 70%", "sizes": ["1 Kg", "250 Gm"] },
        { "name": "TOP GUARD 30%SC", "technical": "Flutriafol + Tebuconazole", "sizes": ["200 Ml", "400 Ml", "800 Ml"] }
    ],
    "INSECTICIDES": [
        { "name": "7 STAR 10% EC", "technical": "Bifenthrin 10% EC", "sizes": ["500 Ml"] },
        { "name": "ACITOX 20% W/V SL", "technical": "Acetamiprid 20%", "sizes": ["500 Ml"] },
        { "name": "ASTRIS GOLD 20% SC", "technical": "Lufenuron 9.5% + Lambda-cyhalothrin 9.5%", "sizes": ["100 Ml"] },
        { "name": "AXXIPROX 10.8%EC", "technical": "Pyriproxyfen 10%", "sizes": ["500 Ml"] },
        { "name": "BOLTON 31%EC", "technical": "Chlorpyrifos + Gamma Cyhalothrin 31% EC", "sizes": ["1 Liter", "400 Ml", "200 Ml"] },
        { "name": "BRANDA 2.5EC", "technical": "Lambda-cyhalothrin 2.5%", "sizes": ["1 Liter", "250 Ml"] },
        { "name": "CHLORPYRIFOS 40EC", "technical": "Chlorpyrifos 40%", "sizes": ["1 Liter", "250 Ml"] },
        { "name": "COMBIPRO", "technical": "Imidacloprid + Tebuconazole", "sizes": ["300 Ml"] },
        { "name": "CYREN 4E 48% EC", "technical": "Chlorpyrifos 48% 4E", "sizes": ["1 Liter", "250 Ml"] },
        { "name": "Cyper+Profenfos", "technical": "Cypermethrin + Profenofos", "sizes": ["1 Liter"] },
        { "name": "DANADIM 40% EC", "technical": "Dimethoate 40% EC", "sizes": ["500 Ml", "1 Liter"] },
        { "name": "DARCO 15% SE", "technical": "Flonicamid + Pyriproxyfen", "sizes": ["250 Ml"] },
        { "name": "DAZZ 18% OD", "technical": "Acetamiprid + Flonicamid", "sizes": ["250 Ml"] },
        { "name": "DOLLAR 440 EC", "technical": "Cypermethrin + Profenofos", "sizes": ["1 Liter"] },
        { "name": "EMAMECTIN BENZ. 1.9EC", "technical": "Emamectin Benzoate", "sizes": ["1 Liter", "400 Ml"] },
        { "name": "GOLD STAR 1.8 EC", "technical": "Abamectin 1.8%", "sizes": ["1 Liter"] },
        { "name": "HACHI-HACHI", "technical": "Tolfenpyrad 15% EC", "sizes": ["200 Ml"] },
        { "name": "INKOTA SUPER 1.6% GR", "technical": "Chlorantraniliprole + Clothianidin", "sizes": ["4 Kg"] },
        { "name": "KANPAI 5% SC", "technical": "Chromafenozide 5% SC", "sizes": ["200 Ml"] },
        { "name": "KILLBOR 0.4%G", "technical": "Fipronil 0.4%", "sizes": ["8 Kg"] },
        { "name": "NEXUS 25% WP", "technical": "Imidacloprid 25%", "sizes": ["250 Gm", "240 Ml"] },
        { "name": "PROFENOFOS 50% EC", "technical": "Profenofos 50% EC", "sizes": ["1 Liter"] },
        { "name": "PIMEKO 80% WG", "technical": "Pymetrozine 60% + Nitenpyram 20%", "sizes": ["120 Gm", "60 Gm"] },
        { "name": "PIRAPROL 30% SC", "technical": "Chlorfenapyr + Chlorantraniliprole", "sizes": ["100 Ml"] },
        { "name": "PIRATE 36SC", "technical": "Chlorfenapyr 360g/L", "sizes": ["100 Ml", "200 Ml"] },
        { "name": "PROPARGITE", "technical": "Propargite 57%", "sizes": ["1 Liter"] },
        { "name": "SPARLA 10.5%", "technical": "Pyridaben 10.2% + Abamectin 0.3%", "sizes": ["1 Liter", "400 Ml"] },
        { "name": "SPONGMEY 5% G", "technical": "Cartap 5%", "sizes": ["7 Kg"] },
        { "name": "TRYCORD 10 EC", "technical": "Cypermethrin 10% EC", "sizes": ["1 Liter"] }
    ],
    "MICRONUTRIENTS": [
        { "name": "BORDOX SUPER 15%", "technical": "Boron 15%", "sizes": ["500 Ml"] },
        { "name": "FURTI NS PLUS", "technical": "NPK 11-0-0 + Sulphur 75%", "sizes": ["10 Kg"] },
        { "name": "HEADLAND MULTI", "technical": "B=1%, Cu=1%, Fe=3%, Mn=1%, Zn=4%", "sizes": ["150 Gm", "500 Gm"] },
        { "name": "HEADLAND ZN 15%", "technical": "Zinc Chelate 15%", "sizes": ["500 Gm", "250 Gm"] },
        { "name": "HI-K", "technical": "K=49.8%, N=4.5%", "sizes": ["500 Ml", "1 Liter"] },
        { "name": "HI-PHOS (Liquid)", "technical": "P=44%, K=7.4%, Mg=8%", "sizes": ["1 Liter"] },
        { "name": "MYCROBOR DF", "technical": "Boron 20%", "sizes": ["1 Kg"] },
        { "name": "NANOCAL", "technical": "Soluble Potash + Calcium + Fulvic Acid", "sizes": ["1 Liter", "500 Ml"] },
        { "name": "NUTRI-AKTIV AMINOALGAE", "technical": "Seaweed Extract + Boron + Nitrogen", "sizes": ["1 Liter", "500 Ml"] },
        { "name": "NUTRICIA K-S 00-36-24", "technical": "Potassium 36% + Sulphur 24%", "sizes": ["1 Liter", "2 Liter"] },
        { "name": "NUTRICIA P-K 00-25-50", "technical": "Phosphorus 25% + Potassium 50%", "sizes": ["2 Liter", "1 Liter"] },
        { "name": "NUTRICIA ZN33", "technical": "Zinc 33%", "sizes": ["1 Liter"] },
        { "name": "OROMATE K26", "technical": "Humic Acid 20% + Potash 6%", "sizes": ["2 Liter"] },
        { "name": "PREMIO", "technical": "Liquid Organic Fertilizer + Fatty Alcohols", "sizes": ["1 Liter", "100 Ml", "200 Ml"] },
        { "name": "SEAMAXX", "technical": "Ascophyllum Nodosum (Bio Stimulant)", "sizes": ["500 Ml"] },
        { "name": "SPEEDFOL - K 10-10-40", "technical": "NPK 10:10:40", "sizes": ["1 Kg"] },
        { "name": "SPEEDFOL - N 28-8-14", "technical": "NPK 28:08:14", "sizes": ["1 Kg"] },
        { "name": "SPEEDFOL - P 12-40-14", "technical": "NPK 12:40:14", "sizes": ["1 Kg"] },
        { "name": "SPEEDFOL CEREAL SP 13-3-41", "technical": "NPK 13-3-41", "sizes": ["1 Kg"] },
        { "name": "SPEEDFOL COTTON SP 15-5-31", "technical": "NPK 15-05-31", "sizes": ["1 Kg"] },
        { "name": "STOP DROP", "technical": "For Premature Fruit Dropping", "sizes": ["1 Liter"] },
        { "name": "SUPERAMIN 30 L", "technical": "Amino Acid + Organic Matter", "sizes": ["800 Ml", "400 Ml"] },
        { "name": "SILIKALZIUM", "technical": "Calcium 31.8% + Silicon 17.4%", "sizes": ["250 ML", "500 ML", "1 Liter"] },
        { "name": "ULTRASOL MICRO REXENE FEQ48", "technical": "Iron EDDHA Ortho-Ortho 4.8%", "sizes": ["1 Kg"] },
        { "name": "ULTRASOL MICRO REXENE FEXQ58", "technical": "Iron HBED Ortho-Ortho 5.8%", "sizes": ["1 Kg"] },
        { "name": "ZINC FORCE 27%", "technical": "Zinc Sulphate Monohydrate 33%", "sizes": ["3 Kg"] }
    ],
    "WEEDICIDES": [
        { "name": "BISPYRIBAC", "technical": "Bispyribac Sodium 18% + Bensulfuron Methyl 12%", "sizes": ["100 Gm"] },
        { "name": "GLYPHOSATE 48%SL", "technical": "Glyphosate 48%", "sizes": ["1 Liter"] },
        { "name": "FULL CLEAR", "technical": "Metolachlor 27.5% + Pendimethalin 13.8%", "sizes": ["1 Liter"] },
        { "name": "PANDIMATHLINE", "technical": "Pendimethalin 33%", "sizes": ["1 Liter"] },
        { "name": "PROTOKEY", "technical": "Clodinafop-Propargyl 20%", "sizes": ["125 Ml"] },
        { "name": "S-METOLACHLOR 960 EC", "technical": "S-Metolachlor 96% EC", "sizes": ["800 Ml"] },
        { "name": "TRI-ULTRA 25% OD", "technical": "Mesosulfuron-Methyl + MCPA-Isooctyl", "sizes": ["400 Ml"] }
    ],
    "ADJUVANTS": [
        { "name": "WETCIT", "technical": "Orange Oil (Adjuvant)", "sizes": ["100 Ml", "400 Ml", "800 Ml"] }
    ]
};
